// events.js - Baza de date cu ID-uri unice și găzduire locală
const eventsData = [
    // --- ANTICHITATE ȘI FORMAREA POPORULUI ---
    { id: "00001", name: "Unificarea triburilor dacice", desc: "Burebista formează primul stat centralizat dac.", year: -82, img: "imagini/00001.jpg" },
    { id: "00002", name: "Primul Război Daco-Roman", desc: "Decebal se confruntă cu armatele lui Traian.", year: 101, img: "imagini/00002.jpg" },
    { id: "00003", name: "Cucerirea Daciei", desc: "Împăratul Traian transformă Dacia în provincie romană.", year: 106, img: "imagini/00003.jpg" },
    { id: "00004", name: "Retragerea Aureliană", desc: "Armata și administrația romană se retrag la sud de Dunăre.", year: 271, img: "imagini/00004.jpg" },
    
    // --- EVUL MEDIU (ÎNTEMEIEREA STATELOR) ---
    { id: "00005", name: "Bătălia de la Posada", desc: "Basarab I înfrânge armata maghiară, obținând independența.", year: 1330, img: "imagini/00005.jpg" },
    { id: "00006", name: "Descălecatul Moldovei", desc: "Bogdan I respinge suzeranitatea maghiară.", year: 1359, img: "imagini/00006.jpg" },
    { id: "00007", name: "Bătălia de la Rovine", desc: "Mircea cel Bătrân respinge invazia otomană a lui Baiazid I.", year: 1395, img: "imagini/00007.jpg" },
    { id: "00008", name: "Bătălia de la Varna", desc: "Cruciada târzie la care participă Iancu de Hunedoara.", year: 1444, img: "imagini/00008.jpg" },
    { id: "00009", name: "Atacul de Noapte", desc: "Vlad Țepeș atacă tabăra sultanului Mahomed al II-lea.", year: 1462, img: "imagini/00009.jpg" },
    { id: "00010", name: "Bătălia de la Vaslui", desc: "Victoria strălucită a lui Ștefan cel Mare contra otomanilor.", year: 1475, img: "imagini/00010.jpg" },
    { id: "00011", name: "Bătălia de la Codrii Cosminului", desc: "Ștefan cel Mare înfrânge armata poloneză.", year: 1497, img: "imagini/00011.jpg" },
    { id: "00012", name: "Învățăturile lui Neagoe Basarab", desc: "Scrierea celebrei opere diplomatice și morale.", year: 1512, img: "imagini/00012.jpg" },
    { id: "00013", name: "Transilvania, Principat Autonom", desc: "După bătălia de la Mohacs, devine vasală Porții.", year: 1541, img: "imagini/00013.jpg" },
    { id: "00014", name: "Bătălia de la Călugăreni", desc: "Mihai Viteazul oprește avansul uriașei armate a lui Sinan Pașa.", year: 1595, img: "imagini/00014.jpg" },
    { id: "00015", name: "Bătălia de la Șelimbăr", desc: "Mihai Viteazul înfrânge oastea lui Andrei Bathory.", year: 1599, img: "imagini/00015.jpg" },
    { id: "00016", name: "Prima Unire a Țărilor Române", desc: "Mihai Viteazul devine domn al Țării Românești, Transilvaniei și Moldovei.", year: 1600, img: "imagini/00016.jpg" },
    { id: "00017", name: "Asasinarea lui Mihai Viteazul", desc: "Ucis pe Câmpia Turzii din ordinul lui Basta.", year: 1601, img: "imagini/00017.jpg" },

    // --- SECOLELE XVII - XVIII ---
    { id: "00018", name: "Pravila lui Vasile Lupu", desc: "Tipărirea primei legi scrise din Moldova.", year: 1646, img: "imagini/00018.jpg" },
    { id: "00019", name: "Biblia de la București", desc: "Prima traducere completă a Bibliei în limba română.", year: 1688, img: "imagini/00019.jpg" },
    { id: "00020", name: "Diploma Leopoldină", desc: "Transilvania trece sub stăpânirea Imperiului Habsburgic.", year: 1691, img: "imagini/00020.jpg" },
    { id: "00021", name: "Începutul Epocii Fanariote", desc: "Instaurarea domnitorilor numiți direct de sultan.", year: 1711, img: "imagini/00021.jpg" },
    { id: "00022", name: "Martiriul Brâncovenilor", desc: "Constantin Brâncoveanu și fiii săi sunt executați la Istanbul.", year: 1714, img: "imagini/00022.jpg" },
    { id: "00023", name: "Epoca Fanariotă în Țara Românească", desc: "Primul domnitor fanariot, Nicolae Mavrocordat.", year: 1716, img: "imagini/00023.jpg" },
    { id: "00024", name: "Anexarea Bucovinei", desc: "Imperiul Habsburgic anexează nordul Moldovei.", year: 1775, img: "imagini/00024.jpg" },
    { id: "00025", name: "Răscoala lui Horea, Cloșca și Crișan", desc: "Revoltă țărănească majoră în Transilvania.", year: 1784, img: "imagini/00025.jpg" },
    { id: "00026", name: "Supplex Libellus Valachorum", desc: "Petiția românilor transilvăneni pentru drepturi politice.", year: 1791, img: "imagini/00026.jpg" },

    // --- SECOLUL XIX (RENAȘTEREA NAȚIONALĂ) ---
    { id: "00027", name: "Pacea de la București", desc: "Basarabia este anexată de Imperiul Rus.", year: 1812, img: "imagini/00027.jpg" },
    { id: "00028", name: "Revoluția lui Tudor Vladimirescu", desc: "Mișcarea ce pune capăt epocii fanariote.", year: 1821, img: "imagini/00028.jpg" },
    { id: "00029", name: "Revenirea la domniile pământene", desc: "Grigore al IV-lea Ghica și Ioniță Sandu Sturdza.", year: 1822, img: "imagini/00029.jpg" },
    { id: "00030", name: "Tratatul de la Adrianopol", desc: "Libertatea comerțului pentru Principatele Române.", year: 1829, img: "imagini/00030.jpg" },
    { id: "00031", name: "Regulamentele Organice", desc: "Primele acte cu rol de constituție introduse sub tutela rusă.", year: 1831, img: "imagini/00031.jpg" },
    { id: "00032", name: "Revoluția Pașoptistă", desc: "„Dreptate, Frăție” - mișcarea democratică europeană.", year: 1848, img: "imagini/00032.jpg" },
    { id: "00033", name: "Tratatul de la Paris", desc: "Înlătură protectoratul rusesc, sudul Basarabiei revine Moldovei.", year: 1856, img: "imagini/00033.jpg" },
    { id: "00034", name: "Adunările Ad-hoc", desc: "Românii își exprimă dorința de unire și autonomie.", year: 1857, img: "imagini/00034.jpg" },
    { id: "00035", name: "Mica Unire", desc: "Alexandru Ioan Cuza este ales domnitor în ambele principate.", year: 1859, img: "imagini/00035.jpg" },
    { id: "00036", name: "Universitatea din Iași", desc: "Se înființează prima universitate modernă din România.", year: 1860, img: "imagini/00036.jpg" },
    { id: "00037", name: "Primul Guvern Unic", desc: "Barbu Catargiu devine primul prim-ministru al României.", year: 1862, img: "imagini/00037.jpg" },
    { id: "00038", name: "Secularizarea averilor mănăstirești", desc: "Un sfert din teritoriul țării reintră în posesia statului.", year: 1863, img: "imagini/00038.jpg" },
    { id: "00039", name: "Reforma Rurală", desc: "Țăranii primesc pământ de la domnitorul Cuza.", year: 1864, img: "imagini/00039.jpg" },
    { id: "00040", name: "Carol I devine Domnitor", desc: "Aducerea prințului străin și adoptarea primei Constituții.", year: 1866, img: "imagini/00040.jpg" },
    { id: "00041", name: "Proclamarea Independenței", desc: "Mihail Kogălniceanu citește declarația în Parlament.", year: 1877, img: "imagini/00041.jpg" },
    { id: "00042", name: "Congresul de la Berlin", desc: "Marile puteri recunosc independența; Dobrogea revine României.", year: 1878, img: "imagini/00042.jpg" },
    { id: "00043", name: "Proclamarea Regatului", desc: "România devine regat, iar Carol I devine primul rege.", year: 1881, img: "imagini/00043.jpg" },
    { id: "00044", name: "Aderarea la Tripla Alianță", desc: "Tratat secret semnat cu Germania și Austro-Ungaria.", year: 1883, img: "imagini/00044.jpg" },
    { id: "00045", name: "Memorandumul Transilvănenilor", desc: "Petiție pentru drepturile etnicilor români din Austro-Ungaria.", year: 1892, img: "imagini/00045.jpg" },

    // --- SECOLUL XX (RĂZBOAIE ȘI UNIRE) ---
    { id: "00046", name: "Zborul lui Traian Vuia", desc: "Primul zbor autopropulsat cu un aparat mai greu decât aerul.", year: 1906, img: "imagini/00046.jpg" },
    { id: "00047", name: "Marea Răscoală Țărănească", desc: "Revoltă sângeroasă din cauza sărăciei extreme a țăranilor.", year: 1907, img: "imagini/00047.jpg" },
    { id: "00048", name: "Al Doilea Război Balcanic", desc: "România obține Cadrilaterul prin Pacea de la București.", year: 1913, img: "imagini/00048.jpg" },
    { id: "00049", name: "Consiliul de Coroană de la Sinaia", desc: "România își declară neutralitatea la începutul WWI.", year: 1914, img: "imagini/00049.jpg" },
    { id: "00050", name: "Intrarea în Primul Război Mondial", desc: "România trece Carpații pentru a elibera Transilvania.", year: 1916, img: "imagini/00050.jpg" },
    { id: "00051", name: "Bătălia de la Mărășești", desc: "„Pe aici nu se trece!” - victorie crucială a Armatei Române.", year: 1917, img: "imagini/00051.jpg" },
    { id: "00052", name: "Unirea Basarabiei", desc: "Sfatul Țării de la Chișinău votează unirea (27 martie).", year: 1918, img: "imagini/00052.jpg" },
    { id: "00053", name: "Marea Unire (Alba Iulia)", desc: "Desăvârșirea statului național unitar român (1 Decembrie).", year: 1918, img: "imagini/00053.jpg" },
    { id: "00054", name: "Tratatul de la Trianon", desc: "Recunoașterea internațională a unirii Transilvaniei.", year: 1920, img: "imagini/00054.jpg" },
    { id: "00055", name: "Încoronarea de la Alba Iulia", desc: "Regele Ferdinand și Regina Maria sunt încoronați.", year: 1922, img: "imagini/00055.jpg" },
    { id: "00056", name: "Constituția României Mari", desc: "Cea mai democratică lege fundamentală din Europa de Est.", year: 1923, img: "imagini/00056.jpg" },
    { id: "00057", name: "Criza dinastică (Restaurația)", desc: "Carol al II-lea se întoarce pe tron, înlocuindu-l pe fiul său, Mihai.", year: 1930, img: "imagini/00057.jpg" },
    { id: "00058", name: "Dictatura Regală", desc: "Carol al II-lea suspendă Constituția și interzice partidele.", year: 1938, img: "imagini/00058.jpg" },
    { id: "00059", name: "Pactul Ribbentrop-Molotov", desc: "România cedează URSS Basarabia și Nordul Bucovinei.", year: 1940, img: "imagini/00059.jpg" },
    { id: "00060", name: "Dictatul de la Viena", desc: "România pierde Nord-Vestul Transilvaniei (August).", year: 1940, img: "imagini/00060.jpg" },
    { id: "00061", name: "Statul Național Legionar", desc: "Abdicarea lui Carol al II-lea; generalul Ion Antonescu ia puterea.", year: 1940, img: "imagini/00061.jpg" },
    { id: "00062", name: "Rebeliunea Legionară", desc: "Antonescu suprimă violent Garda de Fier.", year: 1941, img: "imagini/00062.jpg" },
    { id: "00063", name: "Treceți Prutul!", desc: "Intrarea în Al Doilea Război Mondial împotriva URSS.", year: 1941, img: "imagini/00063.jpg" },
    { id: "00064", name: "Bătălia de la Stalingrad", desc: "Dezastru militar uriaș pentru armatele română și germană.", year: 1942, img: "imagini/00064.jpg" },
    { id: "00065", name: "Întoarcerea Armelor", desc: "Regele Mihai îl arestează pe Antonescu și iese din Axă.", year: 1944, img: "imagini/00065.jpg" },

    // --- COMUNISMUL ---
    { id: "00066", name: "Instalarea guvernului Petru Groza", desc: "Comunizarea forțată a țării impusă de sovietici (6 Martie).", year: 1945, img: "imagini/00066.jpg" },
    { id: "00067", name: "Furtarea Alegerilor", desc: "Partidul Comunist falsifică masiv alegerile parlamentare.", year: 1946, img: "imagini/00067.jpg" },
    { id: "00068", name: "Proclamarea Republicii (RPR)", desc: "Regele Mihai I este forțat să abdice pe 30 Decembrie.", year: 1947, img: "imagini/00068.jpg" },
    { id: "00069", name: "Înființarea Securității", desc: "Aparatul represiv care a terorizat populația decenii la rând.", year: 1948, img: "imagini/00069.jpg" },
    { id: "00070", name: "Aderarea la ONU", desc: "România devine membră a Organizației Națiunilor Unite.", year: 1955, img: "imagini/00070.jpg" },
    { id: "00071", name: "Retragerea trupelor sovietice", desc: "Armata Roșie părăsește teritoriul României.", year: 1958, img: "imagini/00071.jpg" },
    { id: "00072", name: "Ceaușescu preia puterea", desc: "Devine Secretar General și schimbă numele în RSR.", year: 1965, img: "imagini/00072.jpg" },
    { id: "00073", name: "Discursul din balcon", desc: "Ceaușescu condamnă public invadarea Cehoslovaciei de către URSS.", year: 1968, img: "imagini/00073.jpg" },
    { id: "00074", name: "Cutremurul din Vrancea", desc: "Dezastru național (7.2 grade pe Richter) în 4 martie.", year: 1977, img: "imagini/00074.jpg" },
    { id: "00075", name: "Revolta de la Brașov", desc: "Muncitorii de la uzina Steagul Roșu protestează contra regimului.", year: 1987, img: "imagini/00075.jpg" },
    { id: "00076", name: "Revoluția Română", desc: "Căderea sângeroasă a dictaturii comuniste (Decembrie).", year: 1989, img: "imagini/00076.jpg" },

    // --- EPOCA CONTEMPORANĂ ---
    { id: "00077", name: "Piața Universității și Mineriada", desc: "Proteste anticomuniste reprimate violent de mineri (Iunie).", year: 1990, img: "imagini/00077.jpg" },
    { id: "00078", name: "Constituția Democratică", desc: "Adoptarea noii Constituții prin referendum național.", year: 1991, img: "imagini/00078.jpg" },
    { id: "00079", name: "Declarația de la Snagov", desc: "Consens politic național pentru integrarea euro-atlantică.", year: 1995, img: "imagini/00079.jpg" },
    { id: "00080", name: "Aderarea la NATO", desc: "România devine stat membru cu drepturi depline.", year: 2004, img: "imagini/00080.jpg" },
    { id: "00081", name: "Aderarea la Uniunea Europeană", desc: "Tratatul intră în vigoare la 1 ianuarie.", year: 2007, img: "imagini/00081.jpg" },
    { id: "00082", name: "Tragedia de la Colectiv", desc: "Incendiul declanșează proteste masive și demisia guvernului.", year: 2015, img: "imagini/00082.jpg" }
];