const eventsData9 = [
    
];

const eventsData10 = [
    
];

const eventsData11 = [
    { name: "Răscoala Boxerilor", desc: "Rebeliune violentă în China împotriva influenței străine și a imperialismului.", year: 1900 },
    { name: "Premiile Nobel", desc: "Sunt decernate primele Premii Nobel pentru pace, literatură și științe.", year: 1901 },
    { name: "Războiul Burilor", desc: "Se încheie conflictul din Africa de Sud prin victoria britanicilor asupra burilor.", year: 1902 },
    { name: "Primul Zbor", desc: "Frații Wright reușesc primul zbor controlat cu un aparat cu motor.", year: 1903 },
    { name: "Antanta Cordială", desc: "Marea Britanie și Franța semnează acordul care pune bazele viitoarei alianțe.", year: 1904 },
    { name: "Duminica Sângeroasă", desc: "Începe prima Revoluție Rusă, reprimată violent de trupele țariste la Sankt Petersburg.", year: 1905 },
    { name: "HMS Dreadnought", desc: "Britanicii lansează primul cuirasat modern, declanșând cursa înarmărilor navale.", year: 1906 },
    { name: "Crearea Antantei", desc: "Se semnează tratatul anglo-rus, finalizându-se alianța Triplei Înțelegeri.", year: 1907 },
    { name: "Anexarea Bosniei", desc: "Austro-Ungaria anexează Bosnia-Herțegovina, provocând tensiuni majore în Balcani.", year: 1908 },
    { name: "Traversarea Mânecii", desc: "Louis Blériot realizează primul zbor peste Canalul Mânecii cu un avion.", year: 1909 },
    { name: "Revoluția Portugheză", desc: "Monarhia este abolită în Portugalia și este proclamată Prima Republică.", year: 1910 },
    { name: "Cucerirea Polului Sud", desc: "Exploratorul norvegian Roald Amundsen atinge pentru prima dată Polul Sud geografic.", year: 1911 },
    { name: "Primul Război Balcanic", desc: "Statele balcanice se aliază și atacă Imperiul Otoman pentru a elibera teritoriile europene.", year: 1912 },
    { name: "Pacea de la București", desc: "Se încheie Al Doilea Război Balcanic; România obține Cadrilaterul.", year: 1913 },
    { name: "Atentatul de la Sarajevo", desc: "Arhiducele Franz Ferdinand este asasinat, declanșând Primul Război Mondial.", year: 1914 },
    { name: "Arme chimice", desc: "Germania folosește pentru prima dată gazul toxic pe frontul de la Ypres.", year: 1915 },
    { name: "Bătălia de la Verdun", desc: "Cea mai lungă și sângeroasă bătălie de pe Frontul de Vest din Primul Război Mondial.", year: 1916 },
    { name: "Revoluția Bolșevică", desc: "Comuniștii conduși de V.I. Lenin preiau cu forța puterea în Rusia.", year: 1917 },
    { name: "Sfârșitul Marelui Război", desc: "Se semnează armistițiul de la Compiègne. În România are loc Marea Unire.", year: 1918 },
    { name: "Societatea Națiunilor", desc: "La Conferința de Pace de la Paris se creează prima organizație pentru pace mondială.", year: 1919 },
    { name: "Tratatul de la Trianon", desc: "Ungaria semnează tratatul prin care se recunoaște internațional unirea Transilvaniei cu România.", year: 1920 },
    { name: "Noua Politică Economică", desc: "Lenin introduce NEP în Rusia pentru a redresa economia prăbușită după război.", year: 1921 },
    { name: "Marșul asupra Romei", desc: "Fasciștii lui Benito Mussolini preiau puterea în Italia în urma unor presiuni masive.", year: 1922 },
    { name: "Constituția României", desc: "Este adoptată una dintre cele mai avansate și democratice Constituții din Europa.", year: 1923 },
    { name: "Moartea lui Lenin", desc: "Liderul sovietic se stinge din viață, deschizând calea ascensiunii lui Iosif Stalin.", year: 1924 },
    { name: "Pactul de la Locarno", desc: "Marile puteri europene garantează granițele vestice ale Germaniei, instaurând o aparentă pace.", year: 1925 },
    { name: "Germania în Societate", desc: "Republica de la Weimar este acceptată ca membru cu drepturi depline în Societatea Națiunilor.", year: 1926 },
    { name: "Zborul Transatlantic", desc: "Charles Lindbergh traversează Oceanul Atlantic, zburând singur și fără oprire.", year: 1927 },
    { name: "Pactul Briand-Kellogg", desc: "Peste 60 de state semnează un document simbolic prin care scot războiul în afara legii.", year: 1928 },
    { name: "Marea Criză Economică", desc: "Bursa de pe Wall Street se prăbușește (Joia Neagră), aruncând lumea în recesiune.", year: 1929 },
    { name: "Restaurația", desc: "Prințul Carol revine în țară și este încoronat ca Regele Carol al II-lea al României.", year: 1930 },
    { name: "Invadarea Manciuriei", desc: "Japonia atacă și ocupă teritoriul chinez, sfidând autoritatea Societății Națiunilor.", year: 1931 },
    { name: "Alegerea lui Roosevelt", desc: "Franklin D. Roosevelt devine președintele SUA, promițând programul de relansare „New Deal”.", year: 1932 },
    { name: "Ascensiunea lui Hitler", desc: "Adolf Hitler este numit oficial Cancelar al Germaniei, marcând sfârșitul democrației.", year: 1933 },
    { name: "Noaptea Cuțitelor Lungi", desc: "Hitler își elimină brutal rivalii politici și asasinul Ernst Röhm (liderul trupelor SA).", year: 1934 },
    { name: "Legile de la Nürnberg", desc: "Regimul nazist adoptă legile rasiale antisemite care îi lipsesc pe evrei de cetățenie.", year: 1935 },
    { name: "Axa Berlin-Roma", desc: "Se semnează alianța dintre Germania nazistă și Italia fascistă.", year: 1936 },
    { name: "Masacrul de la Nanking", desc: "Trupele japoneze comit atrocități uriașe împotriva populației civile chineze.", year: 1937 },
    { name: "Acordul de la München", desc: "Marea Britanie și Franța cedează presiunilor lui Hitler, permițând dezmembrarea Cehoslovaciei.", year: 1938 },
    { name: "Începutul Războiului", desc: "După semnarea Pactului Ribbentrop-Molotov, Germania invadează Polonia.", year: 1939 },
    { name: "Căderea Franței", desc: "Armata germană ocupă Parisul. România pierde Basarabia, Transilvania de Nord și Cadrilaterul.", year: 1940 },
    { name: "Atacul de la Pearl Harbor", desc: "Japonia bombardează baza navală americană, determinând intrarea SUA în război.", year: 1941 },
    { name: "Bătălia de la Midway", desc: "Victorie americană decisivă în Pacific care oprește expansiunea Imperiului Japonez.", year: 1942 },
    { name: "Capitularea la Stalingrad", desc: "Armata a 6-a germană este zdrobită de sovietici în cea mai sângeroasă bătălie din istorie.", year: 1943 },
    { name: "Debarcarea din Normandia", desc: "Aliații debarcă în Franța (Ziua Z). În România are loc lovitura de stat de la 23 August.", year: 1944 },
    { name: "Hiroshima și Nagasaki", desc: "SUA lansează bombele atomice, Japonia capitulează. Se înființează O.N.U.", year: 1945 },
    { name: "Discursul de la Fulton", desc: "Winston Churchill avertizează lumea că o „Cortină de Fier” a coborât peste Europa.", year: 1946 },
    { name: "Planul Marshall", desc: "SUA oferă un ajutor financiar uriaș pentru reconstrucția țărilor europene distruse de război.", year: 1947 },
    { name: "Declarația Drepturilor", desc: "ONU adoptă Declarația Universală a Drepturilor Omului. Se naște statul Israel.", year: 1948 },
    { name: "Crearea NATO", desc: "Este înființată Alianța Nord-Atlantică pentru a contracara amenințarea sovietică în Europa.", year: 1949 },
    { name: "Războiul din Coreea", desc: "Trupele comuniste din Nord invadează Coreea de Sud, declanșând primul mare conflict al Războiului Rece.", year: 1950 },
    { name: "Crearea CECO", desc: "Franța, Germania de Vest și alte 4 state pun bazele primei comunități europene economice.", year: 1951 },
    { name: "Testul termonuclear", desc: "SUA detonează cu succes prima bombă cu hidrogen (bomba H) în Oceanul Pacific.", year: 1952 },
    { name: "Moartea lui Stalin", desc: "Se stinge din viață dictatorul sovietic, deschizând o perioadă de ușoară „dezghețare” politică.", year: 1953 },
    { name: "Căderea Dien Bien Phu", desc: "Armata franceză este înfrântă în Indochina, marcând sfârșitul imperiului colonial francez în Asia.", year: 1954 },
    { name: "Tratatul de la Varșovia", desc: "URSS și statele-satelit (inclusiv România) creează o alianță militară comunistă ca răspuns la NATO.", year: 1955 },
    { name: "Revoluția din Ungaria", desc: "Revolta anticomunistă de la Budapesta este înecată în sânge de tancurile sovietice.", year: 1956 },
    { name: "Tratatele de la Roma", desc: "Se înființează Comunitatea Economică Europeană (Piața Comună). URSS lansează satelitul Sputnik.", year: 1957 },
    { name: "Retragerea Sovietică", desc: "Armata Roșie este retrasă definitiv de pe teritoriul României, în urma negocierilor.", year: 1958 },
    { name: "Revoluția Cubaneză", desc: "Gherilele conduse de Fidel Castro preiau puterea în Cuba, instaurând un regim comunist.", year: 1959 },
    { name: "Anul Africii", desc: "Nu mai puțin de 17 colonii africane își proclamă independența într-un singur an.", year: 1960 },
    { name: "Primul om în spațiu", desc: "Cosmonautul sovietic Iuri Gagarin efectuează primul zbor spațial. Se ridică Zidul Berlinului.", year: 1961 },
    { name: "Criza Rachetelor", desc: "Descoperirea rachetelor sovietice în Cuba aduce SUA și URSS pe pragul războiului nuclear.", year: 1962 },
    { name: "Asasinarea lui J.F.K.", desc: "Președintele american John F. Kennedy este împușcat mortal în Dallas, Texas.", year: 1963 },
    { name: "Declarația din Aprilie", desc: "Liderii comuniști români își declară oficial autonomia politică și economică față de Moscova.", year: 1964 },
    { name: "Epoca Ceaușescu", desc: "Nicolae Ceaușescu preia funcția de Secretar General al Partidului Comunist Român.", year: 1965 },
    { name: "Revoluția Culturală", desc: "Mao Zedong inițiază o campanie brutală de epurare socio-politică în China comunistă.", year: 1966 },
    { name: "Războiul de Șase Zile", desc: "Israelul atacă preventiv statele arabe vecine, obținând o victorie zdrobitoare.", year: 1967 },
    { name: "Primăvara de la Praga", desc: "Tentativa de reformare a comunismului în Cehoslovacia este oprită brutal de trupele sovietice.", year: 1968 },
    { name: "Aselenizarea", desc: "Echipajul american al misiunii Apollo 11 ajunge pe Lună; Neil Armstrong face primul pas.", year: 1969 },
    { name: "Grupul țărilor nealiniate", desc: "Se consolidează la nivel mondial mișcarea țărilor care refuzau alianța cu SUA sau URSS.", year: 1970 },
    { name: "Tezele din Iulie", desc: "Ceaușescu lansează o mini-revoluție culturală în România, instaurând un cult extrem al personalității.", year: 1971 },
    { name: "Tratatul SALT I", desc: "SUA și URSS semnează primul mare acord istoric de limitare a armamentului nuclear strategic.", year: 1972 },
    { name: "Criza Petrolului", desc: "Țările arabe din OPEC embarghează exporturile de petrol către țările care susțineau Israelul.", year: 1973 },
    { name: "Demisia lui Nixon", desc: "Președintele american Richard Nixon demisionează în urma celebrului scandal de spionaj Watergate.", year: 1974 },
    { name: "Actul de la Helsinki", desc: "Statele lumii semnează Actul final al CSCE, garantând granițele europene și drepturile omului.", year: 1975 },
    { name: "Unificarea Vietnamului", desc: "Vietnamul de Nord și cel de Sud sunt reunite sub un regim comunist după retragerea americană.", year: 1976 },
    { name: "Greva de la Lupeni", desc: "Zeci de mii de mineri din Valea Jiului se blochează în subteran, protestând împotriva regimului Ceaușescu.", year: 1977 },
    { name: "Acordul Camp David", desc: "SUA intermediază semnarea primului tratat de pace între o națiune arabă (Egipt) și Israel.", year: 1978 },
    { name: "Invazia din Afganistan", desc: "Trupele sovietice invadează Afganistanul; în Iran triumfă Revoluția Islamică.", year: 1979 },
    { name: "Solidaritatea", desc: "În Polonia ia naștere primul mare sindicat muncitoresc anticomunist din Europa de Est.", year: 1980 },
    { name: "Legea Marțială", desc: "Regimul comunist polonez scoate armata pe străzi pentru a suprima sindicatul Solidaritatea.", year: 1981 },
    { name: "Războiul Malvinelor", desc: "Marea Britanie intervine militar și învinge Argentina pentru controlul Insulelor Falkland.", year: 1982 },
    { name: "Războiul Stelelor", desc: "Președintele SUA, Ronald Reagan, anunță un program spațial ambițios de apărare anti-rachetă.", year: 1983 },
    { name: "Boicotul Olimpic", desc: "URSS și alte state comuniste refuză să participe la Jocurile Olimpice de vară de la Los Angeles.", year: 1984 },
    { name: "Perestroika și Glasnost", desc: "Mihail Gorbaciov preia conducerea URSS și inițiază ample reforme economice și de transparență.", year: 1985 },
    { name: "Dezastrul de la Cernobîl", desc: "Reactorul 4 al centralei nucleare sovietice explodează, provocând cel mai mare accident radioactiv.", year: 1986 },
    { name: "Revolta de la Brașov", desc: "Muncitorii români ies masiv în stradă, scandând pentru prima dată sloganuri anti-dictatură.", year: 1987 },
    { name: "Retragerea din Afganistan", desc: "Armata sovietică începe retragerea trupelor, acceptând eșecul invaziei începute cu 9 ani în urmă.", year: 1988 },
    { name: "Căderea Comunismului", desc: "Zidul Berlinului este dărâmat. Regimurile comuniste din Europa de Est (inclusiv România) se prăbușesc.", year: 1989 },
    { name: "Reunificarea Germaniei", desc: "Cele două Germanii (RFG și RDG) redevin un singur stat. Nelson Mandela este eliberat din închisoare.", year: 1990 },
    { name: "Destrămarea URSS", desc: "Uniunea Sovietică încetează oficial să mai existe, împărțindu-se în 15 republici independente.", year: 1991 },
    { name: "Tratatul de la Maastricht", desc: "Liderii europeni semnează tratatul care pune bazele politice și economice ale Uniunii Europene moderne.", year: 1992 },
    { name: "Divizarea Cehoslovaciei", desc: "Statul se desparte pașnic, în mod democratic, formând Republica Cehă și Slovacia.", year: 1993 },
    { name: "Sfârșitul Apartheidului", desc: "Nelson Mandela devine primul președinte de culoare ales democratic în Africa de Sud.", year: 1994 },
    { name: "Acordul de la Dayton", desc: "Sub presiunea SUA, se pune capăt sângerosului război civil din Bosnia și Herțegovina.", year: 1995 },
    { name: "Oaia Dolly", desc: "Cercetătorii britanici anunță prima clonare reușită a unui mamifer dintr-o celulă adultă.", year: 1996 },
    { name: "Retrocedarea Hong Kong-ului", desc: "Marea Britanie returnează oficial suveranitatea asupra metropolei către Republica Populară Chineză.", year: 1997 },
    { name: "Banca Centrală Europeană", desc: "Este creată instituția bancară care va coordona și lansa viitoarea monedă unică a Europei (Euro).", year: 1998 },
    { name: "Războiul din Kosovo", desc: "Aviația NATO bombardează Iugoslavia timp de 78 de zile pentru a opri epurarea etnică a albanezilor.", year: 1999 }
];

const eventsData12 = [
    { name: "Cucerirea Daciei", desc: "Dacia devine provincie romană în urma războaielor purtate de împăratul Traian.", year: 106},
    { name: "Retragerea Aureliană", desc: "Armata și administrația romană se retrag la sud de Dunăre din cauza atacurilor.", year: 271},
    { name: "Edictul de la Milano", desc: "Împăratul Constantin cel Mare acordă libertate de cult creștinilor.", year: 313},
    { name: "Așezarea slavilor", desc: "Slavii trec în masă la sud de Dunăre, izolând romanitatea nord-dunăreană.", year: 602},
    { name: "Răscoala asăneștilor", desc: "Frații Petru și Asan declanșează rebeliunea antibizantină la sud de Dunăre.", year: 1185},
    { name: "Diploma Andreană", desc: "Regele maghiar Andrei al II-lea le acordă privilegii sașilor din Transilvania.", year: 1224},
    { name: "Începutul domniei lui Basarab I", desc: "Întemeietorul statului Țara Românească urcă pe tron.", year: 1310},
    { name: "Bătălia de la Posada", desc: "Basarab I înfrânge armata maghiară și obține independența Țării Românești.", year: 1330},
    { name: "Mitropolia Țării Românești", desc: "Patriarhia de la Constantinopol recunoaște prima Mitropolie la Curtea de Argeș.", year: 1359},
    { name: "Independența Moldovei", desc: "Regele Ungariei recunoaște existența statului independent Moldova condus de Bogdan I.", year: 1365},
    { name: "Domnia lui Mircea cel Bătrân", desc: "Începe una dintre cele mai lungi și stabile domnii din Țara Românească.", year: 1386},
    { name: "Anexarea Dobrogei", desc: "Mircea cel Bătrân extinde teritoriul Țării Românești până la Marea Neagră.", year: 1388},
    { name: "Bătălia de la Rovine", desc: "Victoria strălucită a lui Mircea cel Bătrân împotriva sultanului Baiazid I.", year: 1395},
    { name: "Cruciada de la Nicopole", desc: "O armată creștină europeană este înfrântă grav de forțele otomane.", year: 1396},
    { name: "Alexandru cel Bun", desc: "Începutul domniei care aduce stabilitate și prosperitate în Moldova.", year: 1400},
    { name: "Plata tributului", desc: "Mircea cel Bătrân este forțat să accepte plata haraciului către Poartă pentru a evita atacurile.", year: 1415},
    { name: "Răscoala de la Bobâlna", desc: "Cea mai mare răscoală țărănească din Transilvania medievală.", year: 1437},
    { name: "Iancu de Hunedoara", desc: "Marele comandant militar este numit voievod al Transilvaniei.", year: 1441},
    { name: "Campania cea Lungă", desc: "Ofensiva masivă antiotomană a lui Iancu de Hunedoara la sud de Dunăre.", year: 1443},
    { name: "Bătălia de la Varna", desc: "Regele Ungariei moare în luptă, iar cruciada creștină este înfrântă.", year: 1444},
    { name: "Apărarea Belgradului", desc: "Iancu de Hunedoara oprește expansiunea otomană, dar moare de ciumă în tabără.", year: 1456},
    { name: "Ștefan cel Mare", desc: "Începutul domniei glorioase care va marca istoria Moldovei timp de 47 de ani.", year: 1457},
    { name: "Atacul de Noapte", desc: "Vlad Țepeș lansează o lovitură curajoasă în tabăra sultanului Mahomed al II-lea.", year: 1462},
    { name: "Bătălia de la Baia", desc: "Ștefan cel Mare îl înfrânge decisiv pe regele maghiar Matia Corvin.", year: 1467},
    { name: "Podul Înalt", desc: "Cea mai mare victorie a lui Ștefan cel Mare împotriva otomanilor (la Vaslui).", year: 1475},
    { name: "Valea Albă", desc: "Ștefan cel Mare suferă o înfrângere grea la Războieni în fața sultanului.", year: 1476},
    { name: "Pierderea porturilor", desc: "Moldova pierde cetățile strategice Chilia și Cetatea Albă în favoarea turcilor.", year: 1484},
    { name: "Codrii Cosminului", desc: "Armata poloneză invadatoare este zdrobită de forțele lui Ștefan cel Mare.", year: 1497},
    { name: "Moartea lui Ștefan", desc: "Marele domnitor se stinge din viață și este înmormântat la Mănăstirea Putna.", year: 1504},
    { name: "Războiul Țărănesc", desc: "Revolta catastrofală condusă de Gheorghe Doja în Transilvania.", year: 1514},
    { name: "Bătălia de la Mohács", desc: "Regatul Ungariei este zdrobit de otomanii conduși de Soliman Magnificul.", year: 1526},
    { name: "Principat Autonom", desc: "Transilvania devine Principat sub suzeranitate otomană după prăbușirea Ungariei.", year: 1541},
    { name: "Mihai Viteazul", desc: "Urcarea pe tron a domnitorului care va schimba cursul istoriei românilor.", year: 1593},
    { name: "Bătălia de la Călugăreni", desc: "Victorie tactică remarcabilă a lui Mihai Viteazul condusă pe un teren mlăștinos.", year: 1595},
    { name: "Bătălia de la Șelimbăr", desc: "Mihai Viteazul învinge oastea transilvăneană și intră triumfal în Alba Iulia.", year: 1599},
    { name: "Prima Unire", desc: "Mihai Viteazul devine oficial conducătorul tuturor celor trei Țări Române.", year: 1600},
    { name: "Asasinarea voievodului", desc: "Mihai Viteazul este ucis mișelește pe Câmpia Turzii din ordinul generalului Basta.", year: 1601},
    { name: "Moartea lui Matei Basarab", desc: "Se încheie o domnie marcată de un uriaș progres cultural în Țara Românească.", year: 1654},
    { name: "Asediul Vienei", desc: "Armata otomană este înfrântă masiv, marcând începutul declinului puterii turcești.", year: 1683},
    { name: "Biblia de la București", desc: "Prima traducere integrală a Sfintei Scripturi în limba română.", year: 1688},
    { name: "Diploma Leopoldină", desc: "Transilvania intră oficial sub guvernarea și controlul Imperiului Habsburgic.", year: 1691},
    { name: "Pacea de la Karlowitz", desc: "Imperiul Otoman cedează Transilvania către austrieci prin tratat oficial.", year: 1699},
    { name: "Bătălia de la Stănilești", desc: "Înfrângerea lui Dimitrie Cantemir și instaurarea regimului fanariot în Moldova.", year: 1711},
    { name: "Martiriul Brâncovenilor", desc: "Constantin Brâncoveanu și fiii săi sunt executați la Istanbul (Constantinopol).", year: 1714},
    { name: "Fanarioții în Sud", desc: "Este instaurat regimul fanariot și în Țara Românească prin numirea lui Nicolae Mavrocordat.", year: 1716},
    { name: "Pacea de la Passarowitz", desc: "Imperiul Habsburgic anexează Banatul și Oltenia.", year: 1718},
    { name: "Pacea de la Belgrad", desc: "Oltenia este retrocedată Țării Românești de către austrieci.", year: 1739},
    { name: "Desființarea șerbiei", desc: "Constantin Mavrocordat eliberează țăranii din Țara Românească de legarea de glie.", year: 1746},
    { name: "Desființarea veciniei", desc: "Reforma socială este aplicată și țăranilor dependenți din Moldova.", year: 1749},
    { name: "Kuciuk-Kainargi", desc: "Tratatul de pace care oferă Rusiei rolul de protectoare a creștinilor din Imperiul Otoman.", year: 1774},
    { name: "Anexarea Bucovinei", desc: "Imperiul Habsburgic ocupă abuziv partea de nord a Moldovei.", year: 1775},
    { name: "Răscoala lui Horea", desc: "Sângeroasa rebeliune țărănească din Transilvania se încheie cu execuția liderilor pe roată.", year: 1784},
    { name: "Supplex Libellus Valachorum", desc: "Memoriul elitelor prin care se cereau drepturi politice egale pentru românii ardeleni.", year: 1791},
    { name: "Pacea de la București", desc: "Imperiul Rus anexează teritoriul dintre Prut și Nistru (Basarabia).", year: 1812},
    { name: "Revoluția lui Tudor", desc: "Mișcarea condusă de Tudor Vladimirescu pune capăt Epocii Fanariote.", year: 1821},
    { name: "Domniile pământene", desc: "Grigore al IV-lea Ghica și Ioniță Sandu Sturdza preiau tronurile Țărilor Române.", year: 1822},
    { name: "Tratatul de la Adrianopol", desc: "Aduce desființarea monopolului comercial otoman în Principate.", year: 1829},
    { name: "Regulamentul Organic M.", desc: "Primul document cu rol de constituție intră în vigoare în Țara Românească.", year: 1831},
    { name: "Regulamentul Organic T.", desc: "Același pachet de legi modernizatoare este aplicat și în Moldova.", year: 1832},
    { name: "Societatea Filipescu", desc: "O mișcare secretă ce milita pentru abolirea Regulamentelor Organice este descoperită.", year: 1840},
    { name: "Societatea Frăția", desc: "Nicolae Bălcescu, Ion Ghica și Christian Tell înființează nucleul generației pașoptiste.", year: 1843},
    { name: "Revoluția Pașoptistă", desc: "Poporul român se ridică pentru drepturi sociale și naționale, inspirat de mișcările europene.", year: 1848},
    { name: "Convenția de la Balta Liman", desc: "Rușii și turcii reinstaurează controlul total și numesc domni direct pe 7 ani.", year: 1849},
    { name: "Războiul Crimeii", desc: "Conflictul major european degenerează, scoțând Principatele de sub protecția exclusivă a Rusiei.", year: 1853},
    { name: "Congresul de la Paris", desc: "Marile Puteri garantează colectiv autonomia Principatelor Române.", year: 1856},
    { name: "Adunările ad-hoc", desc: "Românii din ambele state votează masiv dorința fermă de unire a Principatelor.", year: 1857},
    { name: "Convenția de la Paris", desc: "Marile Puteri acceptă o unire formală, dictând regulile pentru noul stat.", year: 1858},
    { name: "Dubla alegere", desc: "Alexandru Ioan Cuza este votat domnitor la Iași și la București, înfăptuind Mica Unire.", year: 1859},
    { name: "Unificarea deplină", desc: "Se formează la București primul Guvern unic și primul Parlament unic al României.", year: 1862},
    { name: "Secularizarea averilor", desc: "Aproape un sfert din teritoriul național este confiscat de la mănăstiri și dat statului.", year: 1863},
    { name: "Lovitura de stat", desc: "Cuza dizolvă parlamentul, impune un nou statut și inițiază vasta Reformă Agrară.", year: 1864},
    { name: "Dinastia de Hohenzollern", desc: "Carol I devine domnitor, iar România adoptă una dintre cele mai moderne Constituții din Europa.", year: 1866},
    { name: "Înființarea P.N.L.", desc: "Ion C. Brătianu formează oficial Partidul Național Liberal.", year: 1875},
    { name: "Independența de Stat", desc: "Mihail Kogălniceanu citește în Parlament actul care rupe definitiv legăturile cu Poarta Otomană.", year: 1877},
    { name: "Congresul de la Berlin", desc: "Independența României este recunoscută internațional; Dobrogea revine țării.", year: 1878},
    { name: "Înființarea BNR", desc: "Banca Națională a României își începe activitatea, consolidând economia.", year: 1880},
    { name: "Proclamarea Regatului", desc: "Carol I este încoronat Rege al României cu o coroană din oțel de tun.", year: 1881},
    { name: "Aderarea la Tripla Alianță", desc: "România încheie un tratat secret de alianță cu Germania și Austro-Ungaria.", year: 1883},
    { name: "Memorandumul", desc: "Protestul românilor din Transilvania este trimis direct împăratului de la Viena.", year: 1892},
    { name: "Legea minelor", desc: "Pachet legislativ major ce deschide exploatarea modernă a resurselor subsolului.", year: 1895},
    { name: "Marea Răscoală", desc: "Sărăcia extremă declanșează revolte violente ale țăranilor în toată țara.", year: 1907},
    { name: "Pacea de la București", desc: "După Al Doilea Război Balcanic, România anexează Cadrilaterul.", year: 1913},
    { name: "Consiliul de la Sinaia", desc: "La izbucnirea Războiului Mondial, România decide să își păstreze neutralitatea.", year: 1914},
    { name: "Intrarea în Război", desc: "Armata română trece Munții Carpați pentru eliberarea Transilvaniei.", year: 1916},
    { name: "Eroismul din Moldova", desc: "Bătăliile de la Mărăști, Mărășești și Oituz blochează definitiv ofensiva germană.", year: 1917},
    { name: "Marea Unire", desc: "Basarabia, Bucovina și Transilvania se unesc pe rând cu Regatul României.", year: 1918},
    { name: "Votul Universal", desc: "Se promulgă legea electorală care acordă drept de vot tuturor bărbaților majori.", year: 1919},
    { name: "Tratatul de la Trianon", desc: "Comunitatea internațională recunoaște oficial apartenența Transilvaniei la România.", year: 1920},
    { name: "Reforma Agrară", desc: "Exproprierea marilor moșii permite împroprietărirea a peste 1 milion de țărani.", year: 1921},
    { name: "Încoronarea de la Alba", desc: "Regele Ferdinand și Regina Maria sunt încoronați suverani ai României Mari.", year: 1922},
    { name: "Constituția Unificării", desc: "Se adoptă cea mai democratică și modernă Constituție din istoria de până atunci a țării.", year: 1923},
    { name: "Criza dinastică", desc: "Moartea Regelui Ferdinand I aduce pe tronul țării pe copilul rege Mihai I.", year: 1927},
    { name: "Restaurația", desc: "Prințul Carol se întoarce în țară și este încoronat ca Regele Carol al II-lea.", year: 1930},
    { name: "Grevele de la Grivița", desc: "Muncitorii ceferiști din București protestează masiv din cauza tăierilor salariale.", year: 1933},
    { name: "Dictatura Regală", desc: "Carol al II-lea suspendă democrația, dizolvă partidele și adoptă o constituție autoritară.", year: 1938},
    { name: "Pactul Ribbentrop-Molotov", desc: "Germania și URSS împart Europa; Basarabia este vizată direct de Stalin.", year: 1939},
    { name: "Pierderile teritoriale", desc: "România cedează fără luptă Basarabia, Transilvania de Nord și Cadrilaterul.", year: 1940},
    { name: "Ordinul: Treceți Prutul!", desc: "România intră în Al Doilea Război Mondial alături de Germania împotriva URSS.", year: 1941},
    { name: "Lovitura de la 23 August", desc: "Mareșalul Antonescu este arestat, iar România se alătură coaliției Națiunilor Unite.", year: 1944},
    { name: "Guvernul Petru Groza", desc: "La presiunea tancurilor sovietice, este instaurat primul guvern controlat de comuniști.", year: 1945},
    { name: "Alegerile falsificate", desc: "Blocul comunist câștigă oficial alegerile prin fraudă masivă împotriva partidelor istorice.", year: 1946},
    { name: "Abolirea Monarhiei", desc: "Regele Mihai este forțat să abdice, fiind proclamată Republica Populară Română.", year: 1947},
    { name: "Naționalizarea", desc: "Statul confiscă absolut toate fabricile, băncile și întreprinderile private din țară.", year: 1948},
    { name: "Colectivizarea", desc: "Începe procesul brutal de deposedare a țăranilor de pământ și forțarea lor în C.A.P.-uri.", year: 1949},
    { name: "Tratatul de la Varșovia", desc: "România devine membră fondatoare a alianței militare a blocului sovietic.", year: 1955},
    { name: "Retragerea Sovietică", desc: "Armata Roșie se retrage definitiv de pe teritoriul României.", year: 1958},
    { name: "Epoca Ceaușescu", desc: "Nicolae Ceaușescu preia puterea și promulgă o nouă Constituție (Republica Socialistă).", year: 1965},
    { name: "Momentul Cehoslovacia", desc: "Ceaușescu refuză să invadeze Cehoslovacia, câștigând o uriașă simpatie în Occident.", year: 1968},
    { name: "Tezele din Iulie", desc: "Se declanșează minirevoluția culturală care impune un cult al personalității extrem.", year: 1971},
    { name: "Greva din Valea Jiului", desc: "Zeci de mii de mineri se blochează în subteran pentru a cere condiții de muncă umane.", year: 1977},
    { name: "Revolta de la Brașov", desc: "Muncitorii strigă pentru prima dată „Jos Dictatura!” pe străzile orașului.", year: 1987},
    { name: "Revoluția Română", desc: "Sute de mii de români ies în stradă. Regimul comunist se prăbușește în sange.", year: 1989},
    { name: "Constituția Democratică", desc: "România revine oficial la sistemul multipartid și la garantarea libertăților civile.", year: 1991},
    { name: "Aderarea la NATO", desc: "România obține protecția militară a celei mai mari alianțe de securitate din lume.", year: 2004},
    { name: "Aderarea la UE", desc: "Țara noastră devine membru cu drepturi depline în Uniunea Europeană.", year: 2007}
];
